### ISSUE TITLE
a few SARS-CoV-2 specifics hard coded in data_parser.py

### ISSUE THREAD

**Issue by anwarMZ** [cidgoh/COVID-MVP#180] opened 2023-09-19 20:55 UTC
Replaced following 
> 617 `last_gene_seen = "3' UTR` 
```
first_gene = list(gene_start_positions)[0]
last_gene = list(gene_start_positions)[-1]
last_gene_seen = last_gene
```
> 624 `if gene in {"5' UTR", "3' UTR"}:`
```
if gene in {last_gene, first_gene}:
```

**Comment by ivansg44** [comment] 2023-09-19 21:11
Duplicate of #170

**Closed by ivansg44** 2023-09-19 21:11 UTC
Labels: bug
